spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQDHQPCZM78TBjaQF+nf/FftEikIMFTHw6nYyVBRnVwNAOi0Wd2NWiiAzgCUy2n9CeFxP/h+0UidlNgcTuRilBEUyemF7JoH+gCw1CoGGTqHp3KhWHC72KoTitY3cOmmfEzZjR30On6Spgn3u5Q6BRUf4VcHkALzuUcMnRAqLQrjXNfdFg8bb1253i44m4jbkPzYJqE+MyjfDq7ctcMvhjFpMG5qXOewyUaujtGio1nwTDsMUoImCH6bJdtS6Is01E2qWHz2/KPIYUZdMX6MGJYKk1lqQskV3teDpWSQTjNcmr/8LjqxmgAL4EtByIYNEs4vTND7JP+92uilgynbFJOuqPeH/wbLPBdwRt2tAcN3+43pcUPJphYiAqqk6EDzvz0='
    
token:
  expiration_time: 86400000
  secret: '{cipher}AQAfrUWHajWzdEg7JMHKXAznAHKC+2UY/L9ezib8zugRMx6dA3/GZZtZAf0h5FDhUAi61NLLMbcWk6zXAQm8a1EmfrUmORmg5l5Fh86d6HWb0wPOfOHKmwlDEKH3NjotweXRb3Z7GeqUvnEJ74jn6UMTHGF6OynnLko19XayRWypkqGPAOBK9zBc7+c9nv85Zwdgz9Mh7senXO8iG+0dgxCxtrEGJj7/4W6ZDDXiM+77rXUnBlcaLujYnwVFX8Jg/zbwy2WXvufo0FshwGx0FPRocVvOz3Mhvo65deS+Cu9LSqm0QXKVp4jve3qBtly6x4KSpp15Kzy6BKfZfszPOScYa3c9y3lTR+UaPYv0xj2rO9zyG7/jORYek/PHYwbtyH79OpWumod/m8xCRXypzwn1'

gateway:
  ip: 172.18.0.3

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders